### PR TITLE
Simple authentication. Fixes #3

### LINKED ISSUE #3: Add authentication
One use case with a lot of potential is read-only access. This would allow other research group members/other collaborators/anyone with access to view experiment results.

### PR DESCRIPTION
**Pull request by Hiyorimi**
Sorry for not being around for long, now simple authentication

### CODE REVIEW

**Comment by Hiyorimi** [comment]
@Kaixhin please take a look, when you are available.

**Review by Kaixhin — CHANGES_REQUESTED** [review]
Looks fine to me, but you need to add `http-auth` to `package.json` as well.

**Comment by Hiyorimi** [comment]
Fixed.

**Review by Kaixhin — APPROVED** [review]

**Comment by Kaixhin** [comment]
FYI #3 was mainly about read-only access - that is, being able to view results but not start/delete experiments.

**Pull request merged**
